(display "Testing <nix-embedded-node>") (newline)
(define ast100 (make-nix-embedded-node "let a = 4; b = a + 5; in b"))
(unless (nix-embedded-node? ast100)
  (exit FAIL))
(when (nix-embedded-node? 100)
  (exit FAIL))
(set! result "")
(output-nix-abstract-syntax-tree ast100 fill-result)
(unless (string=? result "let a = 4; b = a + 5; in b")
  (exit FAIL))

(display "Testing <nix-data-node> #t → builtins.true") (newline)
(define ast200 (make-nix-data-node #t))
(unless (nix-data-node? ast200)
  (exit FAIL))
(when (nix-embedded-node? ast200)
  (exit FAIL))
(when (nix-data-node? ast100)
  (exit FAIL))
(set! result "")
(output-nix-abstract-syntax-tree ast200 fill-result)
(unless (string=? result "(builtins.true)\n")
  (exit FAIL))

(display "Testing <nix-data-node> #f → builtins.false") (newline)
(define ast300 (make-nix-data-node #f))
(unless (nix-data-node? ast300)
  (exit FAIL))
(when (nix-embedded-node? ast300)
  (exit FAIL))
(when (nix-data-node? ast100)
  (exit FAIL))
(set! result "")
(output-nix-abstract-syntax-tree ast300 fill-result)
(unless (string=? result "(builtins.false)\n")
  (exit FAIL))

(display "Testing <nix-data-node> 1234.5") (newline)
(define ast400 (make-nix-data-node 1234.5))
(unless (nix-data-node? ast400)
  (exit FAIL))
(when (nix-embedded-node? ast400)
  (exit FAIL))
(when (nix-data-node? ast100)
  (exit FAIL))
(set! result "")
(output-nix-abstract-syntax-tree ast400 fill-result)
(unless (string=? result "(1234.5)\n")
  (exit FAIL))

(display "Testing <nix-data-node> \"➕➖➗✖️🟰\"") (newline)
(define ast500 (make-nix-data-node "➕➖➗✖️🟰"))
(unless (nix-data-node? ast500)
  (exit FAIL))
(when (nix-embedded-node? ast500)
  (exit FAIL))
(when (nix-data-node? ast100)
  (exit FAIL))
(set! result "")
(output-nix-abstract-syntax-tree ast500 fill-result)
(unless (string=? result "(\"➕➖➗✖️🟰\")\n")
  (exit FAIL))

(display "Testing <nix-data-node> (list) → builtins.null") (newline)
(define ast600 (make-nix-data-node (list)))
(unless (nix-data-node? ast600)
  (exit FAIL))
(when (nix-embedded-node? ast600)
  (exit FAIL))
(when (nix-data-node? ast100)
  (exit FAIL))
(set! result "")
(output-nix-abstract-syntax-tree ast600 fill-result)
(unless (string=? result "(builtins.null)\n")
  (exit FAIL))

(display "Testing <nix-data-node> '() → builtins.null") (newline)
(define ast700 (make-nix-data-node '()))
(unless (nix-data-node? ast700)
  (exit FAIL))
(when (nix-embedded-node? ast700)
  (exit FAIL))
(when (nix-data-node? ast100)
  (exit FAIL))
(set! result "")
(output-nix-abstract-syntax-tree ast700 fill-result)
(unless (string=? result "(builtins.null)\n")
  (exit FAIL))

(display "Testing <nix-path-node> . → ./.") (newline)
(define ast800 (make-nix-path-node "."))
(unless (nix-path-node? ast800)
  (exit FAIL))
(when (nix-embedded-node? ast800)
  (exit FAIL))
(when (nix-path-node? ast100)
  (exit FAIL))
(set! result "")
(output-nix-abstract-syntax-tree ast800 fill-result)
(unless (string=? result "( ./. )\n")
  (exit FAIL))

(display "Testing <nix-path-node> this/is/a/path") (newline)
(define ast900 (make-nix-path-node "this/is/a/path"))
(unless (nix-path-node? ast900)
  (exit FAIL))
(when (nix-embedded-node? ast900)
  (exit FAIL))
(when (nix-path-node? ast100)
  (exit FAIL))
(set! result "")
(output-nix-abstract-syntax-tree ast900 fill-result)
(unless (string=? result "( this/is/a/path )\n")
  (exit FAIL))

(exit PASS)
